version: 2.1

orbs:
  python: cjw296/python-ci@1.1

jobs:
  run-tests:
    parameters:
      python:
        type: string
      postgres:
        type: string
    docker:
      - image: circleci/python:<< parameters.python >>
        environment:
          DB_URL: postgresql://postgres@localhost/circle_test
      - image: circleci/postgres:<< parameters.postgres >>-alpine-ram
    steps:
      - run: "sudo apt install postgresql-client"
      - run: "psql -d circle_test -c \"CREATE EXTENSION btree_gist;\" -h localhost -U postgres"
      - python/pip-run-tests

common: &common
  jobs:
    - run-tests:
        matrix:
          parameters:
            python: ['3.6', '3.8']
            postgres: ["10.7", "11.2"]

    - python/coverage:
        name: coverage
        requires:
          - run-tests

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 0 1 *"
          filters:
            branches:
              only: master
